version: "3.4"

services:
  app:
    image: sweapp
    container_name: sweapp_container
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sweapp_db_container
    ports: 
      - "1450:1433"
    environment:
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y