version: "3.4"

services:
  
  appdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sweapp_db
    ports:
     - 8002:1433
    environment:
      ACCEPT_EULA: "Y"
    env_file:
      - .env

  app:
    image: sweapp
    container_name: sweapp_container
    ports:
     - 8001:80 
    depends_on:
      - appdb